### ISSUE TITLE
MetricType is not persisted

### ISSUE THREAD

**Issue by markusgumbel** [informatik-mannheim/Moduro-Toolbox#18]
1) Creation of new metric type F
2) exit program
3) Restart: F is not listed at metric type.

**Comment by MrMorten** [comment]
not a bug, set <property name="hbm2ddl.auto">update</property> from create to update in hibernate.cfg.xml and build maven project again.

hibernate.cfg.xml is located in: "Other Sources"

![unbenannt](https://cloud.githubusercontent.com/assets/4731329/7258271/b481f5c2-e85b-11e4-88bf-1c302895b282.PNG)
